version: '3.7'

services:
  backend:
    restart: always
    build: 
      context: ./backend 
      dockerfile: Dockerfile
    command: gunicorn todo.config.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - database
    networks:
      - main

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - build_folder:/frontend/dist
    networks:
      - main

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - build_folder:/var/www/frontend:ro
    depends_on:
      - backend
      - frontend
    networks:
      - main

  database:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - main

  # traefik:
  #   image: "traefik:v2.3"
  #   container_name: "traefik"

volumes:
  build_folder:
  postgres_data:

networks:
  main: