export DEBUG=1
export SECRET_KEY=foo
export DJANGO_ALLOWED_HOSTS="localhost 127.0.0.1"
export SQL_ENGINE=django.db.backends.postgresql_psycopg2
export SQL_HOST=database
export SQL_PORT=5432
export SQL_PASSWORD=postgres
export POSTGRES_USER=postgres
export POSTGRES_DB=postgres
export DATABASE=postgres