# Generated by Django 3.1.4 on 2021-01-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TodoBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescrTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('update_date', models.DateField(auto_now=True)),
                ('todo_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TodoBase.todo')),
            ],
        ),
    ]
