# Generated by Django 3.1.4 on 2021-01-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TodoBase', '0002_descrtodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descrtodo',
            name='todo_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='TodoBase.todo'),
        ),
    ]
