# Generated by Django 3.1.4 on 2021-01-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoBase', '0003_auto_20210108_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descrtodo',
            old_name='todo_owner',
            new_name='todo',
        ),
    ]
